## NUMPY 

In [2]:
import numpy  as np

In [3]:
#1. Write a program to find and manipulate the shape of ndarray.
# 1-d array
l1=[1,2,3]
arr1 = np.array ([l1])
print(arr1)

[[1 2 3]]


In [4]:
# 2-d array
l2=[4,5,6]
l3=[7,8,9]
arr2 = np.array([[l1],[l2],[l3]])
print(arr2)


[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [5]:
# 3-d array
arr3 = np.array([[[l1],[l2]],[[l3],[l1]],[[l2],[l3]]])
print(arr3)

[[[[1 2 3]]

  [[4 5 6]]]


 [[[7 8 9]]

  [[1 2 3]]]


 [[[4 5 6]]

  [[7 8 9]]]]


In [8]:
#2. Write a program to divide a range into 5 equal parts.
A = np.arange(16).reshape((4, 4))
print('Array A is:')
print(A)
[B,C] = np.hsplit(A, 2)
print('Array B is:')
print(B)
print('Array C is:')
print(C)

Array A is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array B is:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Array C is:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [3]:
#3. Write a program to find the logarithmic value of numbers from 31 to 40.
# Python3 program to find log(n) using Inbuilt

# Function of math library
import math

if __name__ == "__main__":
    n = 31

    print(int(math.log(n, 2)))


4


In [4]:
#4. Write a program to create a 3x2 matrix containing zeros and another matrix containing one only.
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)


First array:
[[0.71794433 0.03470223 0.62085544]
 [0.51049679 0.36232996 0.23208218]
 [0.22734359 0.36895784 0.74009587]
 [0.65779433 0.51979939 0.9599676 ]
 [0.58997202 0.58823785 0.93734611]]
Second array:
[[0.35005847 0.30841467]
 [0.63112664 0.23198108]
 [0.96020705 0.42062918]]
Dot product of two arrays:
[[0.86937376 0.49062474]
 [0.63022677 0.33911893]
 [1.02308794 0.46701326]
 [1.48009338 0.72724743]
 [1.47782362 0.7126912 ]]


In [7]:
#5. Write a program to convert regular array into an ndarray.
# Python program to demonstrate 
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [31]:
#6. Write a program to create an ndarray containing characters of a string.

b = np.array([ 'pawan' ])
b

array(['pawan'], dtype='<U5')

In [33]:
#7. Explain slicing in Numpy.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [34]:
#8. How can we use conditions in Numpy within an array?
# Python program explaining
# where() function

import numpy as np

np.where([[True, False], [True, True]],
        [[1, 2], [3, 4]], [[5, 6], [7, 8]])


array([[1, 6],
       [3, 4]])

In [36]:
#9. Write a program to find transpose of two metrics and then perform addition on them.
# Python3 Program to find
# transpose of a matrix

N = 4

# This function stores
# transpose of A[][] in B[][]

def transpose(A,B):

    for i in range(N):
        for j in range(N):
            B[i][j] = A[j][i]

# driver code
A = [ [1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3],[4, 4, 4, 4]]


B = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]] # To store result

transpose(A, B)

print("Result matrix is")
for i in range(N):
    for j in range(N):
        print(B[i][j], " ", end='')
    print()




Result matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


In [37]:
#10. How to convert an ndarray into a 1D array?
l1=[1,2,3]
arr1 = np.array ([l1])
print(arr1)

[[1 2 3]]


In [38]:
#11. How to remove or add a new dimension in ndarray?
a = np.arange(6).reshape(2, 3)
print(a)

print(a.shape)

print(a[:, :, np.newaxis])

print(a[:, :, np.newaxis].shape)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


In [42]:
#12. How to append, insert and delete new elements in ndarray?
A = []
X = np.ndarray((1,2,3))
A.append(X)

print(A)

[array([[[0.35005847, 0.30841467, 0.63112664],
        [0.23198108, 0.96020705, 0.42062918]]])]


In [43]:
#13. Write a program to explain various string manipulation methods on Numpy arrays.
# Python code to perform arithmetic
# operations on NumPy array


import numpy as np


# Initializing the array
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)

print('First array:')
print(arr1)

print('\nSecond array:')
arr2 = np.array([12, 12])
print(arr2)

print('\nAdding the two arrays:')
print(np.add(arr1, arr2))

print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))

print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))

print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [44]:
#14. Write a program to perform various arithmetic functions on Numpy arrays. 
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

# The same functions and operations can be used for multiple matrices
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)


[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [45]:
#15. Write a program to explain matrix manipulation using ndarrays.
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [47]:
#16. How to perform I/O operations on ndarrays?


## PANDAS

In [ ]:
#17. Explain Series, DataFrame and Panel in Pandas.


In [ ]:
#18. Write a program to concat two DataFrames.


In [ ]:
#19. Write a program to perform custom addition function on a DataFrame.


In [ ]:
#20. Write a program to group a DataFrame by various categories.


In [ ]:
#21. Explain indexing in Dataframe.


In [ ]:
#22. Write a program to merge two DataFrames.


In [ ]:
#23. Write a program to handle missing data from DataFrame.


In [ ]:
#24. Write program to create bar chart, box chart, area plot, scatter plot and pie chart from a DataFrame.


In [ ]:
#25. What is the difference between rand() and randn() methods.


In [ ]:
#26. Explain reindexing in Pandas.


In [ ]:
#27. How to perform sorting on DataFrames.


In [ ]:
#28. How to perform SQL commands like DDL & DML using Pandas.


In [ ]:
#29. Explain string manipulation in Pandas.

## SCIPY

In [ ]:

#30. How to perform algebra operations using Scipy?


In [ ]:
#31. Write a program to perform Fourier transformation.


In [ ]:
#32. Write a program to perform image processing using Scipy.


In [ ]:
#33. How to find integration and interpolation using Scipy?


In [ ]:
#34. Explain I/O operations using Scipy.


## MATPLOTLIB


In [ ]:
#35. Explain different properties of plot() method.


In [ ]:
#36. Write a program to create a line graph using Matplotlib.


In [ ]:
#37. Write a program to create a scatter plot using Matplotlib.


In [ ]:
#38. Write a program to create a bar chart using Matplotlib.


In [ ]:
#39. Write a program to create a histogram using Matplotlib.


In [ ]:
#40. Write a program to create a pie chart using Matplotlib.


In [ ]:
#41. Write a program to plot categorical data using Matplotlib.


In [ ]:
#42. Write a program to add a pinpoint in a graph using Matplotlib.


In [ ]:
#43. Write a program to add extra text into a graph using Matplotlib.


In [ ]:
#44. Write a program to create multiple graph within a graph using Matplotlib.