In [3]:
import numpy  as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#task
#1. exponentation : np.exp(b)

in_array = [1, 3, 5]
print ("Input array : ", in_array)
  
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [22]:
#2. square root : np.sqrt(b)

  
arr1 = np.sqrt([1, 4, 9, 16])
arr2 = np.sqrt([6, 10, 18])
  
print(arr1)
print(arr2)

[1. 2. 3. 4.]
[2.44948974 3.16227766 4.24264069]


In [14]:
#3. print sines of an array : np.sin(a)

in_array = [0, 2, 3]

 
Sin_Values = np.sin(in_array)
print (Sin_Values)

[0.         0.90929743 0.14112001]


In [15]:
#4. element wise cosine : np.cos(d)

in_array = [1, 5, 3]

 
cos_Values = np.cos(in_array)
print (cos_Values)

[ 0.54030231  0.28366219 -0.9899925 ]


In [20]:
#5. element-wise natural logarithm : np.log(a)
 
print( np.log(4**4))
print( np.log(2**8))

5.545177444479562
5.545177444479562


In [ ]:
#6. dot product : C.dot(d)
#hint- shift=tab

In [23]:
#1. practice
#initialize a list
listA = [4, 16, 9, 1, 25, 49]

#find square root of items in the list
output = np.sqrt(listA)

print(output)

[2. 4. 3. 1. 5. 7.]


In [34]:
#2. practice
a = np.array([17, 11, 19]) # 1x3 Dimension array

b = 3 

c = a + b
print(c)

[20 14 22]
