In [3]:
l1 = [1,2,3,4,5,6,7,8]
print(l1)


[1, 2, 3, 4, 5, 6, 7, 8]


In [1]:

# classes ---attrections (charateritistics of dsta) , function(some set instructions to manipulate that data)

In [9]:
# zero dim array
arr1 = np.array([1])
print(arr1)
print(type(arr1))

[1]
<class 'numpy.ndarray'>


In [11]:
# one-dim array
arr2 = np.array([1,2,3,4,5])
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
# two-dim array
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(type(arr3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [16]:
# three-dim array
arr4 = np.array([[[1,2],[7,8]],[[3,4],[9,10]],[[5,6],[11,12]]])
print(arr4)
print(type(arr4))

[[[ 1  2]
  [ 7  8]]

 [[ 3  4]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]
<class 'numpy.ndarray'>


In [17]:
arr4.dtype

dtype('int32')

In [18]:
arr4.shape

(3, 2, 2)

In [19]:
arr4.ndim

3

In [ ]:
# t1 make one-d, two-d and three-d array with list

In [ ]:
#t2 make a two -d of flots

In [ ]:
# t3 access 3rd and 4th element of one-d array, 2nd element of 2nd raw in 2d array, 2nd plane 2nd raw 3rd element of 3d array