In [15]:
import numpy  as np

In [ ]:
# q1- make one-d, two-d and three-d array with list

In [2]:
# 1-d array
l1=[1,2,3]
arr1 = np.array ([l1])
print(arr1)


[[1 2 3]]


In [3]:
# 2-d array
l2=[4,5,6]
l3=[7,8,9]
arr2 = np.array([[l1],[l2],[l3]])
print(arr2)


[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [4]:
# 3-d array
arr3 = np.array([[[l1],[l2]],[[l3],[l1]],[[l2],[l3]]])
print(arr3)

[[[[1 2 3]]

  [[4 5 6]]]


 [[[7 8 9]]

  [[1 2 3]]]


 [[[4 5 6]]

  [[7 8 9]]]]


In [7]:
# q2- make a 2-d array of flots.
print(float("16.54"))

16.54


In [ ]:
# q3- access 3rd and 4th element of one-d array, 2nd element of 2nd raw in 2d array, 2nd plane 2nd raw 3rd element of 3d array.



In [17]:
# access 3rd and 4th element of one-d array

B = np.array ([1,2,3,4,5])
B[3,4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
#2nd element of 2nd raw in 2d array
A = np.array([[1,2,1],[7,5,3],[9,4,8]])
A[0,0]


1

In [ ]:
#2nd plane 2nd raw 3rd element of 3d array.
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])