In [1]:
import numpy  as np

In [4]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1)
print('shape of array :', arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape of array : (12,)


In [8]:
arr1 = arr1.reshape (3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr1 = arr1.reshape (2,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
arr1 = arr1.reshape (4,3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr1 = arr1.reshape (6,2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [15]:
#iterating
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [16]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [ ]:
#brodcasting

In [17]:
A = np.array ([1,2,3,4,5])
print(A)

[1 2 3 4 5]


In [18]:
A*2

array([ 2,  4,  6,  8, 10])

In [19]:
B = np.array([[1,2,1],[7,5,3],[9,4,8]])
print(B)

[[1 2 1]
 [7 5 3]
 [9 4 8]]


In [20]:
C = np.array([[1,2,1],[7,5,3],[9,4,8]])
print(C)

[[1 2 1]
 [7 5 3]
 [9 4 8]]


In [21]:
B+C

array([[ 2,  4,  2],
       [14, 10,  6],
       [18,  8, 16]])

In [22]:
B*C

array([[ 1,  4,  1],
       [49, 25,  9],
       [81, 16, 64]])

In [23]:
B-C

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
d = np.add(C,B)
print(d)

[[ 2  4  2]
 [14 10  6]
 [18  8 16]]


In [29]:
e = np.subtract(C,B)
print(e)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
f = np.divide(C,B)
print(f)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:

#task
# exponentation : np.exp(b)
#square root : np.sqt(b)
#print sines of an array : np.sin(a)
#element wise cosine : np.cos(d)
# element-wise natural logarithm : np.log(a)
#dot product : C.dot(d)
#hint- shift=tab

In [ ]:
#sorting

In [31]:

A1 = np.array([[1,2,1],[7,5,3],[9,4,8]])
print(A1)

[[1 2 1]
 [7 5 3]
 [9 4 8]]


In [32]:
A2 = np.array([[1,4,1],[7,6,3],[9,4,8]])
print(A2)

[[1 4 1]
 [7 6 3]
 [9 4 8]]


In [33]:
A1.sort()
print(A1)

[[1 1 2]
 [3 5 7]
 [4 8 9]]


In [35]:
A1.sort(1)
print(A1)

[[1 1 2]
 [3 5 7]
 [4 8 9]]


In [36]:
A1==A2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [40]:
A1[A1==A2]

array([1])

In [41]:
A1[A1!=A2]

array([1, 2, 3, 5, 7, 4, 8, 9])

In [42]:
A1[A1<A2]

array([1, 3, 5, 4])

In [43]:
A1[A1>A2]

array([2, 7, 8, 9])

In [44]:
A1[A1<=A2]

array([1, 1, 3, 5, 4])

In [47]:
A2[A1>=A2]

array([1, 1, 3, 4, 8])

In [ ]:
# aggregeate fun.

In [48]:
B1 = np.array([[1,4,1],[7,6,3],[9,4,8]])
print(B1)

[[1 4 1]
 [7 6 3]
 [9 4 8]]


In [49]:
B1.sum()

43

In [50]:
#colum-wise sum
B1.sum(axis=0)

array([17, 14, 12])

In [51]:
# raw wise sum
B1.sum(axis=1)

array([ 6, 16, 21])

In [52]:
B1.min()

1

In [53]:
B1.max()

9

In [55]:
B1.min(axis=0)

array([1, 4, 1])

In [56]:
B1.max(axis=1)

array([4, 7, 9])

In [57]:
B1.cumsum()

array([ 1,  5,  6, 13, 19, 22, 31, 35, 43], dtype=int32)

In [58]:
B1.cumsum(axis=1)

array([[ 1,  5,  6],
       [ 7, 13, 16],
       [ 9, 13, 21]], dtype=int32)

In [59]:
B1.cumsum(axis=0)

array([[ 1,  4,  1],
       [ 8, 10,  4],
       [17, 14, 12]], dtype=int32)

In [ ]:
#other operation
# mean - a.mean()
# median - a.median()
#standard deviation -np.std(a)

In [ ]:

#staking
# a= np.vstack()
# a= np.hstack()